version: '3.3'
services:
  app:
    build:
      context: .
    container_name: issues-dashboard-container
    image: issues-dashboard
    ports:
      - "80:4567"
    env_file:
      - .env
    volumes:
      - type: bind
        source: "${PWD}"
        target: /app
        read_only: false
    # command: rerun -b bundle exec "rackup -d -p 4567 -o 0.0.0.0"
    #command: bundle exec "rackup -d -p 4567 -o 0.0.0.0 -E production"
    tty: true
    stdin_open: true