version: '3.3'
services:
  app:
    build:
      context: .
    container_name: issues-dashboard-container
    image: issues-dashboard
    env_file:
      - .env
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: "./"
        target: /app
        read_only: false
    tty: true
    stdin_open: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.github.rule=Host(`github.local`)
      - traefik.http.routers.github.entrypoints=web
      - traefik.docker.network=web
      - traefik.http.services.github.loadbalancer.server.port=4567
    networks:
      - web

networks:
  web:
    external: true